@startuml car
interface Car {
  
     - final  _id: String
      - final  _model: String
       - final  _brand: String
  +car(id:String,model : String, brand:String)
  +getId():String
  +getModel():String
  +getBrand():String
  
}

class CarDao {
    - _carsDb: List<Car>
   
   +findById(carId : String):Car
    + findAll( ): List<Car>
 
}
class CarFormatter {
  
   +getCarsNames(cars: List<Car>): String

}
class CarManager{
    
    - final  _carDao: CarDao
    - final _carFormatter :CarFormatter
      - final _carRater :CarRater

 + CarManager(carDao :CarDao, carFormatter: CarFormatter, carRater :CarRater)
 + getCarById(carId:String):Car
 +String()
 +getBestCar():Car

}
class CarRater{
  +getBestCar(cars:List<Car>):Car
}


CarDao "1" --> "0..*" Car
CarManager"1" --> "1"CarFormatter
CarManager"1" --> "1"CarDao
CarManager"1" --> "1"CarRater

@enduml